#!/bin/bash

# Setup SSH Key on Hetzner Server
# This script helps configure SSH key authentication

echo "🔑 SSH Key Setup for Hetzner Server"
echo "=================================="
echo ""
echo "Follow these steps to add your SSH key to the server:"
echo ""
echo "1. Connect to your server using the rescue password:"
echo "   ssh root@65.109.132.232"
echo "   Password: 7m4pgKd\\P93uA"
echo ""
echo "2. Once connected, run these commands on the server:"
echo ""
echo "   # Create .ssh directory if it doesn't exist"
echo "   mkdir -p ~/.ssh"
echo "   chmod 700 ~/.ssh"
echo ""
echo "   # Add your public key to authorized_keys"
echo "   echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINS+3kKi8XG1IBQV+QFSTf/ewYdQEhj6JZU9zAxDY/ly test-hetzner' >> ~/.ssh/authorized_keys"
echo ""
echo "   # Set correct permissions"
echo "   chmod 600 ~/.ssh/authorized_keys"
echo ""
echo "   # Exit the server"
echo "   exit"
echo ""
echo "3. Test the SSH key connection:"
echo "   ./scripts/hetzner/check-connection.sh"
echo ""
echo "Your SSH key fingerprint should be:"
echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINS+3kKi8XG1IBQV+QFSTf/ewYdQEhj6JZU9zAxDY/ly test-hetzner"
echo ""
echo "After completing these steps, you'll be able to use SSH key authentication!"